# Generated by Django 2.0.13 on 2019-04-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='consumptions',
        ),
        migrations.AddField(
            model_name='consumption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='consumptions',
            field=models.ManyToManyField(to='polls.Consumption'),
        ),
    ]
