# Generated by Django 2.0.13 on 2019-04-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190403_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='consumed_products',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='consumption',
        ),
    ]
