# Generated by Django 2.0.13 on 2019-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190404_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
