# Generated by Django 2.0.13 on 2019-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190403_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='team_member',
            name='product',
            field=models.ManyToManyField(to='polls.Product'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='consumption',
            field=models.ManyToManyField(to='polls.Consumption'),
        ),
    ]
