# Generated by Django 2.0.13 on 2019-04-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190403_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='product',
        ),
        migrations.AddField(
            model_name='team_member',
            name='consumed_products',
            field=models.CharField(default=[], max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='consumption',
            field=models.CharField(default=[], max_length=500),
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
